add_newline = true
right_format = "$cmd_duration"

[line_break]
disabled = false

# Prompt symbols 
[character]
success_symbol = "[ğŸˆ](#a6e3a1 bold)"
error_symbol = "[ğŸˆ](#f38ba8)"
vicmd_symbol = "[ğŸˆ](#f9e2af)"

[package]
disabled = false
 
[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo = false
format = "[î‚¶]($style)[(bg:#89b4fa fg:#49628a)$path](bg:#89b4fa fg:#49628a)[î‚´ ]($style)"
style = "bg:#191724 fg:#89b4fa"

[cmd_duration]
min_time = 1000

[git_commit]
commit_hash_length = 5
only_detached = false
tag_disabled = false

[git_status]
style = "dimmed bright-blue"
staged = "[â— ${count}](yellow) "
modified = "[ !${count}](red) "
ahead = "[â‡¡${count}](bold green) "
diverged = "â‡•â‡¡${ahead_count} â‡£${behind_count} "
behind = "[â‡£${count}]{orange} "

[jobs]
number_threshold = 1

[memory_usage]
disabled = false
format= " $symbol [${ram}( | ${swap})]($style) "
threshold = 70
symbol = "ï¡š"
style = "bold dimmed green"

[java]
symbol = "î‰– "
style = "bold bright-cyan"

[status]
disabled = false
map_symbol = true


[sudo]
disabled = false
